### ISSUE TITLE
Quad Z Option

### ISSUE THREAD

**Issue by PatricLeal** [VoronDesign/Voron-Legacy#10]
Add 4-axis option for Z, option with threaded bar and belt.

**Comment by raymondh2** [comment]
Please elaborate what you mean.

**Comment by PaulNokel** [comment]
Quad Z is not an option for legacy and it is not going to be added officially. Feel free to look into the Z of Trident/V2 and mod it to fit Legacy. Mods are always welcome in https://github.com/VoronDesign/VoronUsers :)
