### ISSUE TITLE
Missing STL files 

### ISSUE THREAD

**Issue by PigeonFX** [VoronDesign/Voron-Legacy#11]
The following STL files are missing from the https://github.com/VoronDesign/Voron-Legacy/releases/tag/V1.0 Zip, (the link from https://vorondesign.com/voron_legacy). But are in the one https://github.com/VoronDesign/Voron-Legacy. 

So, anyone downloading from the website will be missing: 

Electronics > cable_frame_anchor_x10.stl
Gantry > X Carriage > [a]_blower_housing_front.stl
Gantry > X Carriage > blower_housing_rear.stl

**Comment by PaulNokel** [comment]
Electronics > cable_frame_anchor_x10.stl is in the zip file.

Those two are actually missing:
Gantry > X Carriage > [a]_blower_housing_front.stl
Gantry > X Carriage > blower_housing_rear.stl

@FHeilmann I think we need to craft a new zip release file :|

**Comment by FHeilmann** [comment]
I added a new release zip to the Voron-Legacy release which should contain all the missing files. 

Bests,

Florian
