### ISSUE TITLE
LM8UU alternative for triple z Legacy

### ISSUE THREAD

**Issue by PatricLeal** [VoronDesign/Voron-Legacy#24]
Goodnight,
There is a lack of a triple z legacy option for the voron legacy which uses lm8uu which has a lower cost than linear rails.

**Comment by timmit99** [comment]
> which uses lm8uu which has a lower cost than linear rails.

Legacy isn't intended to have a Triple-Z setup. It is an homage to the original Voron 1.x line of printers from early 2016-2018 and will not have major changes done to its mechanics.

If you are looking for a static gantry triple z actuated printer, the Trident is a great choice =)
