### ISSUE TITLE
X gantry mounting to y faulty 

### ISSUE THREAD

**Issue by highrishman** [VoronDesign/Voron-Legacy#4]
The x gantry being mounted to the y by means of 4 m3 bolts into thermal inserts isnt good enough the way the x rails mount into their own holder means when trying to tighten the belts you rack the x gantry , doing this loosens your thermal inserts and pulls them out of the y axis mount meaning you will need to reprint the y axis mounts again and again until you get the printer tight on the first try this is a seriously overlooked issue and i would have the mounting for the rods swapped to the y gantry and use the previous mounting plates be used as purely locking plates with some leeway for racking while tightening belts , appologies for useless english im a bit dyslexic , the suggssted change would also make the x gantry much more rigid as it is fairly flimsy atm

**Comment by highrishman** [comment]
Wrote this as i print my 3rd set of the y axis mounts with the voron emblem 
![16142593209767847791771464886194](https://user-images.githubusercontent.com/79645017/109159414-7c44f780-776c-11eb-9319-2f15348d3f7b.jpg)

**Comment by highrishman** [comment]
If anyone has a good replacement for fusion 360 thats free or atleast a permanent affordable license please suggest them and ill do a crash course on it make the edits and upload the changes i suggest to see if they are up to standard can spend up to around 150€ on a cad software so any suggestions are much appreciated

**Comment by jernejp21** [comment]
Can you show on the model what you mean? I looked the model and I don't see any forces from belts normal to screws. I see only shear stress on screws. Please highlight critical parts.

**Comment by raymondh2** [comment]
Closed due to inactivity.
