### ISSUE TITLE
12mm Z shafts

### ISSUE THREAD

**Issue by edcasati** [VoronDesign/Voron-Legacy#6]
I'm going to be rebuilding a worn out Hypercube that I built 3 years ago as a Voron Legacy. Any way to reuse the 4x12mm Z-shafts that I used originally?
I'm fairly proficient with Fusion 360. If I can get the 3 corresponding part files with the sketches I can probably iterate them myself and feed them back if wanted.

**Comment by raymondh2** [comment]
The CAD files are in the CAD directory.

**Comment by edcasati** [comment]
The ZIP file contains the assembled parts, but not the designs for the parts themselves.

**Comment by raymondh2** [comment]
Correct. That is the complete cad model. We do not use sun assembly files for most designs
